### PR TITLE
properly generate challenge

### PR DESCRIPTION
**Pull request by banksdev**

### CODE REVIEW

**Review by BBPL — CHANGES_REQUESTED** [review]
I don't think heapless package is needed here, we should consider removing that

**Comment by banksdev** [comment]
@BBPL unnecessary crates have been removed from `tempor`

**Review by pKorsholm — APPROVED** [review]
lgtm, I dont fancy the twoline generate_challenge but w/e

**Review by BBPL — APPROVED** [review]
lgtm, agree with @pKorsholm

**Pull request merged**
